### ISSUE TITLE
Fixes for 1.1.1 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#110]
- [x] Compiler reg limit error: https://github.com/svaarala/duktape/issues/111
- [x] Segfault / assertion error in call handling: https://github.com/svaarala/duktape/issues/107
- [x] CJK/Hangul identifier name: https://github.com/svaarala/duktape/issues/103
- [x] Function parsing bug: https://github.com/svaarala/duktape/issues/106
- [x] Compiler pass 3 for corner case shuffle: https://github.com/svaarala/duktape/issues/115
- [x] Add Duktape 1.1.1 release to RELEASES.rst in master
- [x] Note the above bugs in Duktape 1.1 release notes => not done, RELEASES.rst should cover this
- [x] Note the above bugs in Duktape 1.0 release notes (as fixed in Duktape 1.1.1) => mark as obsolete release in release notes
