### ISSUE TITLE
Fixes for 1.6.1 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1174]
- [x] 16-bit fields + no refcounting compile fix #1207
- [x] RegExp dash assert #1250
- [x] duk_hstring arridx overflow #1273 #1276
