### ISSUE TITLE
Fixes for 1.1.2 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#119]
- [x] LHS eval order issue, #118
- [x] Regexp class zero escape, #122
- [x] Return tailcall and comma expression, #131
- [x] Enum shuffle bug, #132
- [x] PUTPROP shuffle bug, #135

There was no burning need to fix this in 1.1.2 so skipped:
- Consider fixing buffer assignment coercion issue, #125
