### ISSUE TITLE
Miscellaneous 3.0.0 release issues

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1217]
- [ ] duk_(p)eval / duk_(p)compile API calls have a lot of variants and behavior is not always intuitive (e.g. duk_(p)eval defaults to `__FILE__` as the .fileName of the eval source, so that a file/line from the eval code is quite misleading); https://github.com/svaarala/duktape/issues/713#issuecomment-215681481 - #738
- [ ] duk_put_prop_list(), replaced by a more extensible and generic mechanism; provide a backwards compatibility extra? - #575
- [ ] API to halt execution: https://github.com/svaarala/duktape/issues/549
- [ ] JC serialization format
- [ ] Rework buffer mixing semantics (if not already done), see e.g. https://github.com/svaarala/duktape/pull/484#issuecomment-162953409
- [ ] Incompatible improvements / deprecations to debugger API calls, some cases are awkward now, see https://github.com/svaarala/duktape/issues/546
- [ ] Rename duk_get_(u)int() to duk_get_(u)int_clamped() to make semantics more explicit
- [ ] Simplify provision of default alloc functions, or perhaps remove them altogether?

**Comment by fatcerberus** [comment]
#549 is already implemented in master (`duk_debugger_pause()`), that shouldn't be on the list. ;)

**Comment by svaarala** [comment]
Thanks, missed that.
