### ISSUE TITLE
Features and fixes for 1.7.0 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1222]
- [x] duk_is_buffer_data() #1221
- [x] duk_push_buffer_object() fix for ArrayBuffer .byteOffset and .byteLength #1229
- [x] RegExp dash assert #1250
- [x] duk_hstring arridx overflow #1273 #1276
- [x] Refzero asserts #1318
- [x] duk_push_heapptr() asserts #1317
- [x] heap->finalize_list and asserts #1321
- [x] ROM pointer slow refcount duk_heaphdr_incref() fix #1320
- [x] Heaphdr signed left shift #813
- [x] ROM object environment provideThis #1340
- [x] Recursive mark-and-sweep entry in certain conditions #1347
- [x] Global/eval redeclare fix #1354
- [x] Stale 'act' pointer in pre/post inc/dec #1371
- [x] A few other stale 'act' pointers #1373
- [x] duk_is_constructor_call() on empty callstack #1376
- [x] Debugger Throw notify on empty callstack #1377
- [x] Module source with trailing // comment #1395
