### ISSUE TITLE
Misc fixes for 2.0.0 releases

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1223]
Miscellaneous fixes and cleanups for release:
- [x] Review release entries and merge / reorder #1245
- [x] Review 2.0 release notes, summarize changes, etc #1245
- [x] Add TextEncoder/TextDecoder to guide built-ins section; while it's not Duktape specific, it's not part of ES #1231
- [x] Resolve configure.py warnings re: unused config options #1232
- [x] Resolve compiler warnings #1233
- [x] README check #1235
- [x] 2.0.0 milestone description
- [x] Guide getting started bulk to Wiki - #1240 https://github.com/svaarala/duktape-wiki/pull/118
- [x] Guide C type background discussion to Wiki - #1240
- [x] Guide ES2015+ status to Wiki, link from Guide - #1240 https://github.com/svaarala/duktape-wiki/pull/147
- [x] Rename ES6 references to ES2015, ES7 references to ES2017 - #1240
- [x] Fix Dukweb example, ArrayBuffer.allocPlain()
