### ISSUE TITLE
Fixes for 2.0.1 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1269]
- [x] String.prototype.repeat() copy_size #1270
- [x] Exponentiation operator, gcc -O2 #1272
- [x] duk_hstring arridx overflow #1273 #1276
- [x] typedarray .set(undefined) crash #1285 #1286
- [x] TextEncoder().encode() final_len #1293 #1294
- [x] Refzero asserts #1318
- [x] duk_push_heapptr() asserts #1317
- [x] heap->finalize_list and asserts #1321
- [x] ROM pointer slow refcount duk_heaphdr_incref() fix #1320
