### ISSUE TITLE
Fixes for 2.0.2 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1331]
- [x] 'duk' bytecode loading #1334
- [x] ROM object environment provideThis #1340
- [x] Android log2 fix #1341
- [x] Recursive mark-and-sweep entry in certain conditions #1347
- [x] Global/eval redeclare fix #1354
- [x] Solaris, HPUX, AIX portability improvements #1356
- [x] Stale 'act' pointer in pre/post inc/dec #1371
- [x] A few other stale 'act' pointers #1373
- [x] duk_is_constructor_call() on empty callstack #1376
- [x] Debugger Throw notify on empty callstack #1377
- [x] Module source with trailing // comment #1395
- [x] Incorrect Duktape.Thread.prototype class number #1402
- [x] Thread 'resumer' refcounts #1407
- [x] duk_tval_decref_norz() fix #1410

**Comment by fatcerberus** [comment]
@svaarala Warnings currently in master for MSVC x64 (they were annoying me :)

```
duk_bi_string.c(295): warning C4267: 'function': conversion from 'size_t' to 'duk_int_t', possible loss of data (compiling source file ..\src\shared\duktape.c)
duk_bi_string.c(782): warning C4267: 'function': conversion from 'size_t' to 'duk_uint_fast32_t', possible loss of data (compiling source file ..\src\shared\duktape.c)
duk_debugger.c(2095): warning C4267: 'function': conversion from 'size_t' to 'duk_uint_t', possible loss of data (compiling source file ..\src\shared\duktape.c)
duk_heap_stringcache.c(113): warning C4267: '=': conversion from 'size_t' to 'duk_uint_fast32_t', possible loss of data (compiling source file ..\src\shared\duktape.c)
duk_hstring_misc.c(82): warning C4267: '=': conversion from 'size_t' to 'duk_uint32_t', possible loss of data (compiling source file ..\src\shared\duktape.c)
```

**Comment by svaarala** [comment]
@fatcerberus Thanks, I'll fix those. They've come about since the lazy string charlen change.

**Comment by svaarala** [comment]
The side effect protection reworks are too big to be included in a patch release so I'll push 2.0.2 out. If a backport of the side effect changes is made for 2.0.x, it'll need to be specifically backported.

**Comment by fatcerberus** [comment]
> Global/eval redeclare fix #1354

It'll be good to get this fix into miniSphere. :)
