### ISSUE TITLE
Misc string handling improvements

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1363]
- [x] Rewrite the string table structure and algorithm. There are currently two separate algorithms (default one and low memory one) and ideally there would be only one. Adding link pointers to `duk_hstring` might be a useful improvement as it would simplify some of the string table maintenance compared to current code. #1277
- [x] Use a better hash for the string table. Current hash uses a MOD operation and doesn't achieve particularly good load factor compared to performance. #1277
- [ ] For some applications delayed string freeing might be useful. When objects become unreachable, they can't spawn back; however, strings can because the same string can be created right after becoming unreachable. For example, doing a lot of substring operations creates substrings that might be reused. A delayed string freeing mechanism would only free strings on a stringtable resize, based on their reference count.
- [ ] Efficient support for string concatenation idioms, see e.g. https://github.com/svaarala/duktape/pull/1277#issuecomment-272223986.
- [ ] Lazy charlen #1303
- [ ] Cache charlen in strcache, at least when charlen field is disabled (make for-loop on str.length limit efficient)
- [ ] Rework strcache to be faster
- [ ] Miscellaneous improvement ideas #1301
