### ISSUE TITLE
Fixes for 1.1.3 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#137]
- [x] Duktape.act() line numbers: #143
- [x] A few compile warnings: #141
- [x] Switch statement default clause first: #155
