### ISSUE TITLE
Second round of performance improvements

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#139]
- [x] JSON fast paths for character lookups in various places (eat whitespace, decode string, decode number, etc), will be merged with #209
- [x] JSON.stringify() fast path #204
- [x] JSON.stringify() buffer append improvement, will be merged with #209
- [x] Add basic compile perftest cases
- [x] Lexer tokenization improvements #207
- [x] Compiler bytecode emit improvements, will be merged with #209
- [x] Avoid current activation lookup in bytecode execution loop by using a current bytecode pointer in a stable place (e.g. `thr->curr_pc`) #265
- [x] Improve on `thr->curr_pc` dispatch by using a local `curr_pc` pointer #294
- [x] Use a 'consts' pointer in executor stack frame instead of on-the-fly consts lookup #295

**Comment by JoshEngebretson** [comment]
Sami!  Do you think either of these would help JSON.stringify?

Have a good mini-vacation :camel:

**Comment by svaarala** [comment]
So far I've been optimizing mostly mechanisms that impact a lot of things like value stack manipulation etc. String hashing and interning is similar in that it affects a lot of code, JSON.stringify() included. 

The best improvement for JSON would come from optimizing it specifically - it now relies on the ordinary value stack API to walk through objects etc, and would be much faster if it just looked inside objects like e.g. mark-and-sweep does.

I'll add a specific JSON.stringify test to this second round.

**Comment by svaarala** [comment]
I'll need to do some actual profiling of the JSON serialization code but one obvious thing is that the serialization code uses duk_hobject_get_enumerated_keys() to get an object key list. This is slow because two temporary objects get created (one for an enumerator and another for the key list).

This can be fixed so that only one temporary object is created. This would be better and would work in all cases.

Another fix is to walk the object properties directly without creating a temporary object. The problem with this is that some JSON.stringify() features work against this. E.g. a replacer callback might mutate the object being walked. Granted these are corner cases, but they are required to work :)

There are probably a few similar issues in the JSON implementation that should be relatively easy to fix - much of this code hasn't been optimized or profiled so far.

**Comment by svaarala** [comment]
It seems that it's possible to improve compile time by roughly 10% with lexer/tokenization changes (faster codepoint window handling, and reworking the main tokenizer function):

```
sva@keppihevonen:~/duktape$ time sudo nice -20 ./duk.master.O2 perf-testcases/test-compile-mandel.js 

real	0m20.129s
user	0m20.094s
sys	0m0.011s
sva@keppihevonen:~/duktape$ time sudo nice -20 ./duk.O2 perf-testcases/test-compile-mandel.js 

real	0m18.017s
user	0m18.000s
sys	0m0.007s
```

I'll finalize the changes and merge in a few days.

**Comment by fatcerberus** [comment]
Awesome, compile time was always my main complaint with Duktape, so if you can make it faster that's great.

Runtime performance of course continues to blow me away as always. :)

**Comment by svaarala** [comment]
The current lexer first decodes input bytes into a codepoint window and the actual tokenizer then looks at the codepoint window instead of source bytes directly. This is obviously not the fastest way to tokenize, but it adds flexibility going forwards: the input encoding only affects the codepoint window part (should it become relevant to support more encodings), and it will be possible to add support for streaming the source from e.g. flash (which will be quite useful for low memory devices) in small chunks. String literals also get decoded and re-encoded from codepoint values so they always come out "normalized" which is nice.

**Comment by JoshEngebretson** [comment]
Did you ever have a chance to look at JSON generation with JSON.stringify(value)?

**Comment by svaarala** [comment]
I did have an initial look: https://github.com/svaarala/duktape/issues/139#issuecomment-83291802

Some gains will be possible by addressing those issues. I've been quite busy with buffer work and other related stuff though, so I'll try to get into that shortly. Sorry :-)

In addition to that, the current buffer handling is probably quite sub-optimal so I'll probably try what happens if I rewrite that. The current dynamic buffer datatype supports a "buffer spare" which allows shared append handling for e.g. JSON and lexer/compiler, but it's much slower than direct buffer management would be. I might remove the entire buffer spare concept at some point because it's only used internally anyway.

Much more could be optimized by having a separate fast path algorithm which didn't support all the specification features like replacement values and perhaps indenting. This would be somewhat annoying to maintain but may be necessary as an optional feature at some point.

**Comment by svaarala** [comment]
@JoshEngebretson Added #204 for this specific task so the discussion is better contained.

**Comment by fatcerberus** [comment]
Just noticed this in the checklist:
"Optimize string intern "compute UTF-8 character length" algorithm which is a major string performance bottleneck"

I wonder if this could be the cause of the slow text rendering in my game engine...?  I assumed it was my font rendering that was slow, but...

**Comment by svaarala** [comment]
@fatcerberus I wouldn't think so - the number of cycles taken to render a character would probably be orders of magnitude larger than the UTF-8 length computation. The "botteleneck" is a bit misleading because we're talking about micro-benchmarks here :)

Also, the character length computation only happens when new strings are introduced. For example, all constant strings in a function are interned at compile time and there's no runtime cost for precomputing their UTF-8 length.

**Comment by fatcerberus** [comment]
Ah, I kind of figured that anyway, but wanted to make sure.

**Comment by svaarala** [comment]
Did several experiments on replacing the string hash and the UTF-8 character length computation but they didn't have a measurable impact on the perf tests - needs a little bit more investigation so I moved these to 1.4. It's probably useful to perf test these on low end hardware too because they have different cpu/memory performance balance.

**Comment by svaarala** [comment]
Moved the function self-reference issue to 1.4 because call optimization work is scheduled for 1.4 and there's not enough time to work it out in 1.3.
