### ISSUE TITLE
Fixes for 2.0.3 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1418]
- [x] RETCONSTN bogus assert with refcount disabled #1433
- [x] Stale duk_tval in duk_inspect_value() #1453
- [x] Symbol Object .valueOf() #1459
- [x] RegExp groups parsing #1463
- [x] Proxy deleteProperty stale duk_tval #1482
- [x] Bound function value stack reserve #1504
- [x] duk_hbufobj assert fix #1506
