### ISSUE TITLE
Features and fixes for 1.8.0 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1419]
- [x] Include current time in PRNG seeding as in 2.x #1446
- [x] Object property table out-of-memory fix #1426
- [x] RegExp groups parsing #1463
- [x] Proxy deleteProperty stale duk_tval #1482
- [x] Bound function value stack reserve #1504
- [x] duk_hbufobj assert fix #1506
- [x] duk_{check,require}_stack_top() reserve #1536
- [x] Protected call nrets/nargs validation fix #1553

**Comment by svaarala** [comment]
The side effect fixes are quite extensive from a backporting perspective so they're not included in the 1.8.0 maintenance release; I'm not sure if they'll be done for 1.x, but if so, it would be in 1.9.0 (#1648).
