### ISSUE TITLE
HTML comment syntax cleanups and improvements

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1437]
- [x] Releases entry for initial merges, #1435 and #1436 - #1438
- [x] Testcase coverage for https://github.com/svaarala/duktape/pull/1435#issuecomment-289179347 - #1438
- [x] Config option for the added syntax (footprint impact is around +120 bytes) - #1438
- [x] Website documentation -> not necessary, Wiki Post-ES5 features now covers these
- [x] Shared code for skipping to end of line? - #1438
- [x] Wiki post-ES5 issues documentation - https://github.com/svaarala/duktape-wiki/pull/166
