### ISSUE TITLE
Fixes for 2.1.1 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1505]
- [x] Bound function value stack reserve #1504
- [x] duk_hbufobj assert fix #1506
- [x] MSVC cast warning #1511 => not relevant for 2.1.x (code structure changes)
- [x] duk_dump_function() .length handling when both .length and _Formals are missing #1516
- [x] Reflect.construct() extra argument fix #1518
- [x] duk_{check,require}_stack_top() reserve #1536
- [x] Debugger GetHeapObjInfo key list #1540
- [x] Protected call nrets/nargs validation fix #1553
- [x] RegExp class dash parsing #1570
- [x] Unary op regression #1624

**Comment by svaarala** [comment]
For duk_dump_function() the fix needs to be backported without affecting bytecode dump/load format. Easiest fix might be to just drop an empty _Formals array on bytecode load.
