### ISSUE TITLE
Unicode support improvements

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1622]
Short term improvements:
- [ ] Allow external toupper, tolower, idchar, ES6 normalization etc operations - #1613
- [ ] Switch to Unicode XML input format - #1085
- [x] BMP canonicalization lookup (workaround)
- [ ] RegExp case insensitive canonicalization skip bitmap - #1616
- [ ] Toupper/tolower skip bitmaps

Long term improvements:
- [ ] Case conversion data structure with a proper tree/index/skip (replacement or non-low-memory option)
- [ ] Membership check data structure with a proper tree/index/skip (replacement or non-low-memory option)
- [ ] Faster data structure for RegExp charclasses: currently list of ranges which can be very slow for a lot of ranges
- [ ] For RegExp charclasses in list of ranges format: sort and merge ranges, use "dontcare" information in case insensitive regexps to merge seemingly discontinuous ranges
- [ ] Data structures to support [String.prototype.normalize()](https://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.normalize), i.e. NFC, NFD, NFKC, NFKD normalization
