### ISSUE TITLE
Fixes for 1.9.0 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1648]
- [ ] Side effect fixes (backported) from #1427?
- [ ] StepOut + tailcall #1685
- [ ] instanceof dangling 'proto' pointer #1725
- [ ] new Function() trailing single line comment #1757
- [ ] Assertion fixes (e.g. compiler bare arrays)

**Comment by dbohdan** [comment]
Should this issue still be open?

**Comment by svaarala** [comment]
Yeah, it's unlikely this release will be made, there would be too much to backport.
