### ISSUE TITLE
Fixes for 2.1.2 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1676]
- [x] MSVC2015 ARM pointer size detection #1675
- [x] StepOut + tailcall #1685
- [x] instanceof dangling 'proto' pointer #1725
- [x] new Function() trailing single line comment #1757
- [x] Thread termination related dangling pointer #1845
