### ISSUE TITLE
Fixes for 1.2.2 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#171]
- [x] Casts for MSVC warnings with fastints: #172
- [x] Lowmem compile error: #174
- [x] Cast warnings: #177
- [x] Review fix, `duk_is_{dynamic,fixed}_buffer()` NULL pointer dereference: #206

**Comment by svaarala** [comment]
Fixes merged and pushed to v1.2-maintenance.
