### ISSUE TITLE
Fixes for 2.2.1 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1760]
- [x] new Function() trailing single line comment #1757
- [x] DUK_BOOL_MIN/DUK_BOOL_MAX #1769
- [x] Debugger StepOver nested tailcall #1787
- [x] Thread termination related dangling pointer #1845
