### ISSUE TITLE
Fixes for 2.2.2 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#1911]
- [ ] Crash with DUK_USE_TRACEBACKS disabled #1909
- [x] Skip DUK_USE_FATAL_HANDLER warning with DUK_USE_CPP_EXCEPTIONS defined, cherry pick the genconfig fix only from #1915
- [ ] Object.getOwnPropertySymbols() fixes #1979
- [ ] Missing `DUK_DCERROR_UNSUPPORTED` when RegExp support disabled #1991

**Comment by mike-lischke** [comment]
May I suggest: suppress warning:

> genconfig.py          WARNING Recommended config option DUK_USE_FATAL_HANDLER not provided

when `DUK_USE_CPP_EXCEPTIONS` is defined (which makes the fatal handler obsolete).

**Comment by svaarala** [comment]
@mike-lischke I can make that change as it's technically correct.

But it's actually a semi-open issue what should be done with C++ and an uncaught exception -- although the dummy exception thrown propagates out of Duktape and can be caught by the caller, it is still unsafe to continue (maybe not in practice in some common cases, but there are no guarantees of safety either).

**Comment by mike-lischke** [comment]
Can you create a dedicated fatal runtime exception? Catching that tells the application should shutdown gracefully *now*, in opposition to other non-fatal issues.

**Comment by svaarala** [comment]
Sure, that would be one option for handling fatal errors. This was left undecided at the initial C++ exception support stage.

There's just one internal exception type now, `duk_internal_exception`. What's your opinion, should a `duk_fatal_exception` inherit from this or be a separate exception?

To me it would make sense for them to not be in an inheritance relationship because:
- `duk_internal_exception` should never be caught by user code.
- `duk_fatal_exception` could be caught by user code so it's not "internal".

**Comment by svaarala** [comment]
Also, `duk_internal_exception` intentionally doesn't inherit from any base class to minimize the chance of someone trying to catch it.

Should `duk_fatal_exception` inherit from some standard class?

**Comment by mike-lischke** [comment]
Yes, makes sense to make them unrelated exception.

**Comment by svaarala** [comment]
Looking at the internals it's probably easier to just add a single `duk_fatal_exception` but give it a message (like the `DUK_USE_FATAL_HANDLER` counterpart).

**Comment by mike-lischke** [comment]
A single fatal exception should be enough, indeed.

**Comment by svaarala** [comment]
C++ exception discussion continues in #1915.

**Comment by svaarala** [comment]
Cancelling this maintenance release as 2.4.0 has a lot of fixes that are hard to backport.
