### ISSUE TITLE
Cleanups for 1.3.0 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#203]
- [x] Recheck bytecode dump/load number constant loading: should have fastint check
- [x] Executor restart after NEW operation to support debugger breakpoints correctly
- [x] Side effect torture; fake call in every refzero queue pump? #304
- [x] Side effect torture; mark-and-sweep fake finalizer #313
- [x] Add refzero and mark-and-sweep finalizer torture to release checklist
- [x] duk_tval pointer warning without DUK_OPT_FASTINT
- [x] Release notes: Duktape.modLoaded[] cache entry change
- [x] Release notes: behavior change for module load error (de-register module instead of keeping partial module in cache)
- [x] Release notes: debugger breakpoint behavior change
- [x] Expand code policy check coverage to Ecmascript testcases and example code
- [x] Clean up FIXMEs from Ecmascript testcases and expand code policy check coverage
- [x] JSON stringify fastpath portability assumption ("%lld" format and "long long" type) => postponed to #325
- [x] Add a minimal Travis test (codepolicycheck)
- [x] Extend Travis setup to run the basic API and Ecmascript tests
- [x] Remove hard Ant/Java dependency from make dist (needed for closure which is not critical)
- [x] Add .gitattributes for LF #317
- [x] Add C++ comments to code policy check
- [x] Allow build with codepolicycheck failures, but reject Travis test
- [x] Mark bufferobject API calls experimental (minor tweaks may happen in 1.4)
- [x] Finalize release notes
- [x] Cleanup for make dist, see: https://github.com/svaarala/duktape/commit/1288329963030ff82e00be2b51e40d540dcc2db2#commitcomment-13002075
- [x] Fix issues from side effect torture tests => tracked in #314, fixed after 1.3.0 unless there are issues that can be triggered with actual user code (and not just by internal torture testing)
- [x] Update index page LOC, lowmemory startup size, code footprint (with buffer support)
- [x] Update index page and README features list, check that they match
- [x] Review experimental API call tags
- [x] Compilation test: Linux x86 and x64, gcc and clang
- [x] Compilation test: Linux x32 gcc
- [x] Compilation test: Windows x86 and x64, MSVC and Cygwin/Mingw, Windows DLL
- [x] Compilation test: OSX
- [x] Compilation test: Linux MIPS gcc
- [x] Compilation test: Linux ARMEL gcc
- [x] Compilation test: Linux SH4 gcc
- [x] Compilation test: embedded mixed endian ARM Linux, gcc - works but has some cast issues (already present in 1.2), #336

**Comment by fatcerberus** [comment]
So, how far off is 1.3? :wink:

**Comment by svaarala** [comment]
For minor releases the release scope doesn't need to be fixed in advance, so I'm not really sure :)

But I'd at least want to complete the buffer-related changes so that they didn't need further changes right away. There are also several small performance improvements to be completed and merged, but none of them are mandatory to make the release a useful improvement over the previous one.

I had originally planned to incorporate an initial step for the `duk_config.h` change (#64) in this release. That's still possible but I'd want to make sure the disruption to users is minimal so it'd also be possible to postpone that to the next release.

**Comment by svaarala** [comment]
I'm doing some issue pruning for 1.3 release - unfortunately some wish list items must be postponed so that the new features in 1.3 (over 1.2) can make an official release. Sorry! :( Feel free to point out if I postponed something critical.

**Comment by svaarala** [comment]
Moved a few more issues to 1.4 - ther stuff left for 1.3 is basically buffer and `duk_config.h` cleanups which should be possible to complete in by early next week.

**Comment by svaarala** [comment]
The main thing left for 1.3 will be compiler and platform testing and checking for warning-free compilation (at least with defaults).

**Comment by svaarala** [comment]
With a telnet session open and no ping running there seems to be no problem with running for hours:

```
~ # uptime
 13:57:03 up 6 min, load average: 2.17, 1.72, 0.82
~ # while true; do date; uptime; sleep 300; done
Fri Sep 11 13:57:10 MEDT 2015
 13:57:10 up 6 min, load average: 2.23, 1.74, 0.83
Fri Sep 11 14:02:10 MEDT 2015
 14:02:10 up 11 min, load average: 1.44, 1.63, 1.04
Fri Sep 11 14:07:10 MEDT 2015
 14:07:11 up 16 min, load average: 1.42, 1.38, 1.09
Fri Sep 11 14:12:11 MEDT 2015
 14:12:11 up 21 min, load average: 1.15, 1.21, 1.10
Fri Sep 11 14:17:11 MEDT 2015
 14:17:11 up 26 min, load average: 1.47, 1.30, 1.16
Fri Sep 11 14:22:11 MEDT 2015
 14:22:11 up 31 min, load average: 1.40, 1.26, 1.17
Fri Sep 11 14:27:11 MEDT 2015
 14:27:11 up 36 min, load average: 1.20, 1.21, 1.17
Fri Sep 11 14:32:11 MEDT 2015
 14:32:11 up 41 min, load average: 1.40, 1.27, 1.20
Fri Sep 11 14:37:11 MEDT 2015
 14:37:11 up 46 min, load average: 1.48, 1.33, 1.24
Fri Sep 11 14:42:11 MEDT 2015
 14:42:11 up 51 min, load average: 1.49, 1.29, 1.24
Fri Sep 11 14:47:11 MEDT 2015
 14:47:11 up 56 min, load average: 1.50, 1.26, 1.23
Fri Sep 11 14:52:11 MEDT 2015
 14:52:11 up  1:01, load average: 1.52, 1.23, 1.22
Fri Sep 11 14:57:11 MEDT 2015
 14:57:11 up  1:06, load average: 1.56, 1.30, 1.24
Fri Sep 11 15:02:11 MEDT 2015
 15:02:11 up  1:11, load average: 1.60, 1.35, 1.27
Fri Sep 11 15:07:11 MEDT 2015
 15:07:11 up  1:16, load average: 1.39, 1.29, 1.25
Fri Sep 11 15:12:11 MEDT 2015
 15:12:11 up  1:21, load average: 1.43, 1.27, 1.25
Fri Sep 11 15:17:11 MEDT 2015
 15:17:11 up  1:26, load average: 1.61, 1.31, 1.26
Fri Sep 11 15:22:11 MEDT 2015
 15:22:11 up  1:31, load average: 1.53, 1.27, 1.25
Fri Sep 11 15:27:11 MEDT 2015
 15:27:11 up  1:36, load average: 1.67, 1.30, 1.25
Fri Sep 11 15:32:11 MEDT 2015
 15:32:11 up  1:41, load average: 1.53, 1.26, 1.24
Fri Sep 11 15:37:11 MEDT 2015
 15:37:11 up  1:46, load average: 1.65, 1.29, 1.25
Fri Sep 11 15:42:11 MEDT 2015
 15:42:11 up  1:51, load average: 1.53, 1.26, 1.24
Fri Sep 11 15:47:11 MEDT 2015
 15:47:11 up  1:56, load average: 1.43, 1.21, 1.21
Fri Sep 11 15:52:11 MEDT 2015
 15:52:11 up  2:01, load average: 1.58, 1.29, 1.24
Fri Sep 11 15:57:11 MEDT 2015
 15:57:11 up  2:06, load average: 1.64, 1.30, 1.25
Fri Sep 11 16:02:11 MEDT 2015
 16:02:11 up  2:11, load average: 1.81, 1.38, 1.28
Fri Sep 11 16:07:11 MEDT 2015
 16:07:11 up  2:16, load average: 1.06, 1.27, 1.26
...
```

**Comment by svaarala** [comment]
There are compile warnings with all low memory options enabled (in particular non-verbose error messages). These were also present in 1.2 and are quite messy to try to eliminate.

**Comment by svaarala** [comment]
Mixed endian ARM linux target with a gcc-3 based toolchain has warnings:

```
duk_tval.c:22: warning: `duk_tval_set_number_chkfast' declared inline after being called
duk_tval.c:70: warning: `duk_tval_get_number_packed' declared inline after being called
duk_util_bufwriter.c:281: warning: `duk_raw_read_u16_be' declared inline after being called
duk_util_bufwriter.c:293: warning: `duk_raw_read_u32_be' declared inline after being called
duk_util_bufwriter.c:305: warning: `duk_raw_read_double_be' declared inline after being called
duk_util_bufwriter.c:323: warning: `duk_raw_write_u16_be' declared inline after being called
duk_util_bufwriter.c:334: warning: `duk_raw_write_u32_be' declared inline after being called
duk_util_bufwriter.c:345: warning: `duk_raw_write_double_be' declared inline after being called
duk_replacements.c:78: warning: `duk_repl_isinf' defined but not used
```

There seems to be some variability in older compilers in where inline attributes are allowed/warned about. This will need revisiting after 1.3 release.

**Comment by svaarala** [comment]
There's also a double-to-integer cast issue on the same exotic ARM target, which is triggered by Node.js Buffer and DataView, tracked in #336. Similar issues are possible on targets where double-integer casts are broken.

**Comment by svaarala** [comment]
To clarify above, these double-to-integer cast issues have been present before and affect other libraries too, so it's not a new issue introduced in this release.

**Comment by fatcerberus** [comment]
Oddly, there appear to be double-to-integer cast issues with MSVC instrumented profiling as well.  I mentioned this before, but the double-to-int64 self-test fails on some machines under the profiler.

You wouldn't thinking converting float to integer would be this hard... :)

**Comment by svaarala** [comment]
Minor trivia is merged to master now. I'm starting the release prep branch and finalize the release in a few hours. If you have any issues with master, now it's the time to say so :-)

**Comment by fatcerberus** [comment]
Yay, Duktape 1.3 is coming!  From what I've seen already, it was worth the wait. :smile:

**Comment by svaarala** [comment]
Still running release checklist tests, these torture tests and assertion enabled tests take a lot of time :) Hopefully they'd be automated one day, not yet though :dog:

**Comment by svaarala** [comment]
Release is tagged and binaries built. Next up is updating the website.

**Comment by svaarala** [comment]
Website is updated now also :-) :beer:

**Comment by fatcerberus** [comment]
Thanks Sami, now I can move forward with minisphere 2.0 and make ArrayBuffers a more pervasive part of my API. :smile:

**Comment by svaarala** [comment]
You're welcome :)

**Comment by svaarala** [comment]
Posted the performance numbers to the Wiki here: http://wiki.duktape.org/Performance130.html

**Comment by fatcerberus** [comment]
Nice, a solid improvement across the board.  One thing jumps out at me though: The buffer object tests.  The performance on those improved by A LOT!  What changed?

**Comment by svaarala** [comment]
I added a fast path for them so that working with buffer objects would be similar to working with plain buffers. Prior to that buffer objects didn't have a fast path - which basically meant every numbered index lookup would cause a string conversion for the key etc.
