### ISSUE TITLE
Fixes for 1.2.3 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#213]
- [x] Execution timeout regression #212
- [x] Execution timeout corner case fixes (rework counter tracking); not obvious if should be merged as the change is not trivial and fixes only corner case #214 => Decided not to merge
- [x] Heap pointer compression compilation issue on x64 #228 (Tested by compiling ajduk on x64)
- [x] JX -Infinity parsing issue #247
- [x] Error.prototype .fileName and .lineNumber toString() #254

**Comment by svaarala** [comment]
FYI, I'll push out the 1.2.3 release in the coming days with the fixes in the description.
