### ISSUE TITLE
Fixes for 2.6.0 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#2212]
- [x] Allow unlabelled function statement in strict mode #2213
- [x] Remove big endian assumption for PPC64 to support ppc64le #2267
- [x] Debugger duk_opcodes.yaml fix (TRYCATCH), add CALL flags #2277
- [x] Fix out-of-memory handling for nested errors #2290
- [x] duk_suspend() main thread state fix #2282
- [x] Update UglifyJS version from 2.4.12 to 3.9.2 (it only affects runtests), fix test breakage due to 2.4.12 artifact paths changing #2299
- [x] CBOR.encode() assertion failure for zero-size dynamic plain buffer #2318
- [x] Add recursion limits and native stack check to CBOR encode/decode #2340
- [x] Fix String.prototype.startsWith/endsWith() pointer overflow #2320
- [x] Fix object hash part handling in enumeration sorting #2322
- [x] Fix unstable pointer in putvar #2323
- [x] Fix unsafe JSON.stringify() behavior if replacer is an array, and Array.prototype has index properties #2324
- [x] Fix RegExp exec() result inherited index handling #2325
- [x] Fix Proxy 'ownKeys' postprocess handling when Array.prototype has index properties #2326
- [x] Fix dangling pointer in coroutine yield() #2332
- [x] Fix JSON.parse() assertion failure and potentially unlimited recursion for JSON.parse() #2341
- [x] duk_logging.c s(n)printf() warning fix #2349
- [x] Fix String.prototype.replace() pointer handling when search string longer than input string #2358
- [x] Better missing PyYAML warning #2361
- [x] NaN normalization fix #2362
- [x] Remove 64kb limit of 'duk' interactive input (when no linenoise enabled) #2368

**Comment by warmwaffles** [comment]
@svaarala is this still relevant since 3.x changes are on the horizon?

**Comment by svaarala** [comment]
2.x will get maintenance for bugs and security issues probably for a long while, because the update to 3.x will not be seamless.

**Comment by warmwaffles** [comment]
@svaarala cool, was just picking through the repository trying to figure out what changed so I can prepare for it.

**Comment by svaarala** [comment]
Main changes so far (some merged, some planned):
- Rewrite of object representation and property algorithms to be faster, more ES2015+ compliant, and enable implementing data structures like Map etc
- Rewrite of Python tooling into Node.js, more dog-fooding of JS, and the tooling will also run with Duktape to improve portability of tooling
- Switch from CESU-8 string representation to WTF-8, this is not visible to ECMAScript code but C code will then see proper UTF-8 strings rather than CESU-8 surrogate pairs for non-BMP codepoints, this simplifies corner case handling in C code (although it's a bit awkward for Duktape internals which must present the surrogate pairs to script code)

With the window open to break stuff, priority is on changes that have compatibility impact but are necessary going forward.

API changes will be minimal so the changes in application code won't be difficult in this sense. But one must be aware of changes under the hood, for example the string representation change affects native code a bit.
