### ISSUE TITLE
Third round of performance improvements

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#259]
- [x] Add support for fast returns, should improve Emscripten performance which suffers a lot from longjmp - #342
- [x] Remove longjmp use from all return handling - #345
- [x] Remove longjmp use from all break/continue handling - #348
- [x] Performance fix for `dbg_processing` check in executor hot path - #371
- [x] Move bytecode executor setjmp() and longjmp handler into a separate external function: improves performance and facilitates using C++ exceptions for longjmp - #370
- [x] Rewrite value stack index check primitives using unsigned arithmetic to reduce code size - #389
- [x] Change valstack policy for values above top (now wiped, change to assume garbage/undefined, based on which is faster) - #389
- [x] Separate internal tags for unused and undefined - #396
- [x] Direct valstack access for "this" coercion - #397
- [x] duk_push_this() direct valstack access
- [x] Check relevance of union in `duk_tval` for Emscripten performance => converting `duk_tval` to a struct has a small but not radical impact
- [x] Test refzero queueing all types (strings etc) so that queueing can be inlined; refzero queue handler can finalize strings too (this should make it faster to wipe large tval ranges and use a single refzero queue check; queueing can be inline so there'd no refzero call) => This is not currently possible because strings don't have a prev/next pointer in their heap header
- [x] Add `DUK_TVAL_SET_xxx_UPDREF()` macros to replace currently repeated idiom, provide slow/fast variants, and optimize for `DUK_TVAL_SET_TVAL_UPDREF()` which is used by e.g. LDREG, LDCONST, etc - #393 #394
- [x] Check performance effect of removing explicit `fun` from executor - #370
- [x] Optimize string intern "compute UTF-8 character length" algorithm which is a major string performance bottleneck - #422
- [x] Improve string hashing performance by using a much more sparsely sampled hash - #432
- [x] Simplify JSON.stringify() indent handling for the slow path (now uses dynamic indent string etc) - #444
- [x] Extend JSON.stringify() fast path to include indentation (but not replacer callback) - #445
- [x] Extend JSON.stringify() fastpath for JX/JC encoding - #445
- [x] JSON.stringify() cycle detection improvement for slow path - #446
- [x] Better bytecode for `x = 123.4` when source is a number (double or ldint compatible) and target is a register-bound variable - #380

**Comment by JoshEngebretson** [comment]
Just wanted to drop a line that we're still looking really forward to the longjmp updates :)

As a side note, we put the full Atomic Runtime source under the MIT license, that's 100% of the code that goes into end user redistributable binaries :+1:

**Comment by svaarala** [comment]
@JoshEngebretson Yeah - I've revived the fast return branch and I'll post something for you soon to see what impact it has with Emscripten.

**Comment by fatcerberus** [comment]
> steal one bit from A into opcode

Won't stealing even a single bit from the A slot reduce the register shuffle limit by half?

**Comment by svaarala** [comment]
Yes, it's a tradeoff between starting to shuffle for smaller functions (those using 128-255 registers; relatively large functions already) but gaining dispatch performance for smaller functions.

**Comment by svaarala** [comment]
Refzero queueing heap objects without a type check might be worth while so that large blocks of tagged values could be efficiently DECREF'd and heap objects with zero refcount could be queued without doing a more detailed type check. The current implementation checks for refzero and if that happens, calls a helper to switch on the heap type and either free directly (strings and buffers) or queue for refzero handling (objects, which have further references and potentially a finalizer).

This is unfortunately not currently possible: strings don't have a prev/next pointer at all in their heap header, so at least a specific check for strings would be needed.

**Comment by fatcerberus** [comment]
> Improve string hashing performance by using a much more sparsely sampled hash

What does this mean, in concrete terms?

**Comment by svaarala** [comment]
Just that by making the string hash more sparse it'd perform (slightly) better. The downside is that the hash quality will be lower. The string hashes are just used in the string table and object property table hash maps so they don't need to be very good, just good enough for that purpose.
