### ISSUE TITLE
Suggestions what to deprecate in Duktape 2.0

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#260]
With 2.0 release it's possible to deprecate some features as compatibility doesn't have to be guaranteed. This issue is for suggestions what features can/should be removed: rarely used features, features which aren't useful in practice, awkward APIs that should be replaced, etc.

I'll be doing a source code scan to come up with candidates for removal too (both compatible and incompatible).

Issues:
- [x] File I/O API calls (move to separate, optional module) - #734
- [x] Dependency of DUK_FPRINTF() - #734
- [x] duk_dump_context_stdout() and duk_dump_context_stderr(): they rely on DUK_FPRINTF() and I/O and are a portability issue (duk_dump_context() can be kept, but might be better as a separate extra) - #736
- [x] duk_safe_call() without userdata argument - #727
- [x] Remove `Duktape.Buffer`, replace with `ArrayBuffer` throughout, e.g. plain buffers should object coerce to `ArrayBuffer` - #739
- [x] Reduce number of custom error types (`DUK_ERR_UNCAUGHT_ERROR` etc) and make remaining custom errors actual Error subclasses: https://github.com/svaarala/duktape/issues/476#issuecomment-162260223 - #740
- [x] Remove option for refcounting only, as there are current features which depend on a back-stop mark-and-sweep (e.g. debugger paused state GC handling) #1168
- [x] Remove error code from fatal errors / panics
- [x] Remove panic vs. fatal distinction, and only use fatal errors?

**Comment by fatcerberus** [comment]
Deprecate everything and rewrite it all from scratch!  It'll be more fun than a barrel of half-witted (spider)monkeys! ;-)

Okay, no, but seriously, I know you mentioned moving the file system functions into a separate module, would that count as deprecation?

**Comment by svaarala** [comment]
I think so: some API calls currently depend on accessing files or stdout/stderr. In hindsight I don't think that's a good idea (at least by default) because an embedded engine should really consult the host environment for such things. It's not just a theoretical issue either, I've personally worked in weird environments where the usual assumptions don't hold (e.g. writes to stdout end up on a device screen, and file system is *not* accessed using ANSI file calls but a proprietary API).

So either Duktape shouldn't provide APIs that depend on I/O (providing them as an optional extra would be fine IMO) or such dependencies need to be very easy and clean to retarget. Current date/time is a similar host dependency which is not very easy or clean to replace at the moment.

**Comment by JoshEngebretson** [comment]
This is (probably far from a full list, but things we hold important:

coroutines, disabling voluntary GC

One thing I would like deprecated is all locals being held by function closures ;)

**Comment by fatcerberus** [comment]
@JoshEngebretson
Off-topic but is there a specific reason you disable voluntary GC?

**Comment by JoshEngebretson** [comment]
From a rather long email exchange:

"The impact of DUK_OPT_NO_VOLUNTARY_GC is that Duktape will never
mark-and-sweep unless it encounters an alloc/realloc error.  When that
happens it mark-and-sweeps to satisfy the allocation.

I would actually recommend that option to you in general, because
refcounting will tend to keep memory usage quite tight - only objects
in reference loops will need mark-and-sweep.  You can run
mark-and-sweep in e.g. menu transitions or such just to reset the
situation from time to time."

The issue we were having was finalizers being run with objects then being rescued, I believe in the same frame.

**Comment by fatcerberus** [comment]
@JoshEngebretson Hm, I think I'll leave the voluntary GC on for minisphere.  Many objects in my engine such as Images and Mixers wrap limited native resources (GPU textures, audio voices...) and I wouldn't want them to end up not getting freed just because their JS representation happens to end up in a reference cycle (yes, `Duktape.gc()` is a thing, but I consider that an "expert" feature).  Nowadays you're nearly always going to run out of other system resources before you run out of memory. :)

@svaarala As for deprecation, maybe the `noresult` variants of eval calls?  It seems easy enough to just issue a `duk_pop();` after the eval if you really don't need the result.  These are just extra API bloat.

I also haven't found `duk_get_uint()` to be particularly useful.  Every time I think I've found a good use case for it, I end up changing my mind and doing one of the following: 1) Cast the result of `duk_get_number()` instead, *throwing* if the number is negative, or 2) Realize that `duk_get_int()` is actually sufficient.

Admittedly it does have some utility on platforms where `sizeof(unsigned int) == sizeof(size_t)`, for sizing things, but even in that case, an out of range value is better treated as an error rather than clamping it (e.g. if I request a 5GB size for something but `sizeof(unsigned int) == 4`, I'd want to see an error instead of having `duk_get_uint()` silently clamp it to 4GB).

**Comment by svaarala** [comment]
Regarding Josh's case - I could never reproduce the issue that Josh was having, and I'm not sure why `DUK_OPT_NO_VOLUNTARY_GC` helps there.

`DUK_OPT_NO_VOLUNTARY_GC` is intended for timing sensitive environments where you don't want an occasional GC pause for objects in reference cycles (but are willing to request for that explicitly when it suits you).

**Comment by JoshEngebretson** [comment]
@svaarala This had to do with objects being rescued, after having their finalizer called. This might refresh your thoughts on it:

"Ok, so I think that the voluntary GC is hitting at times when mark and
sweep is finalizing some objects, which are then rescued.  (I have
verified that the objects which have had finalize run with them are
still in the VM and used after the finalization, so they have not been
GC'd which would make me think they were definitely recused.)

This is fine for "normal" javascript objects with no native backing,
however upon the first finalize (I don't know if there will be a
second), I need to clean up the native side.

If I turn off voluntary gc and then GC every 5 seconds or so,
everything appears to be working as expected.  The "nodes" in this
case do have circular references and so must use mark and sweep, they
only get GC'd every 5 seconds.

This is actually preferable, so while I would absolutely love to know
*exactly* why the voluntary mark and sweep is finalizing/rescuing
objects (which I am pretty sure is happening), I don't think I should
have it on in the first place."

**Comment by svaarala** [comment]
@JoshEngebretson I remember the case, but I couldn't reproduce the issue you were having so I couldn't fix the underlying cause. If GC is working correctly, this shouldn't happen regardless of voluntary GC.

**Comment by JoshEngebretson** [comment]
@svaarala Ok, as long as DUK_OPT_NO_VOLUNTARY_GC isn't on the chopping block, we're good :)  I might be able to boil down a repro case once we get the next build of Atomic in people's hands.  

Once you have generated the list of candidates it would be great to have a look to give any feedback.

**Comment by svaarala** [comment]
@JoshEngebretson I'll gather the suggestions to the description later on - just wanted to open this issue early for discussion :)

**Comment by fatcerberus** [comment]
Maybe deprecate the JC serialization format?

JSON is the canonical format, JX is useful for debugging (I'm using it in my own client for the variable viewer, it's quite nifty), but JC.... I don't know, I haven't really found a niche for it.  You either use `JSON.stringify()` if you need portability or JX for debugging, JC seems... superfluous.

**Comment by svaarala** [comment]
@fatcerberus I tend to agree - the point for JC was that you could serialize arbitrary values into standard JSON so that if a peer wanted plain JSON and you'd want to know there were e.g. buffers in the data, you could see them (instead of them being just silently dropped). Plain JSON just drops a lot of values (you can't e.g. serialize an Infinity or NaN).

But that could also mostly be solved by adding `.toJSON()` methods for buffers, pointers, and such. That's what Node.js does for Buffers to get them JSON-serialized. This would still not solve serialization of `undefined`, NaNs, infinities, etc, though.

**Comment by fatcerberus** [comment]
Yeah, I never understood why JSON was designed that way, it makes it very difficult to work with as a serialization format when JS supports all these values but you can't actually save them out because `JSON.stringify()` will silently drop them from the representation.

Of course, since JC breaks the JSON spec anyway and therefore probably has to be parsed using `eval`, I think at that point I would just serialize in JX.  At least then I'd *know* it will deserialize back to the same object.

**Comment by svaarala** [comment]
JC output is valid JSON though, that's the point of the format: encode as many values in a reasonable manner but keep the output JSON compatible. That's why special values are encoded as boxed objects.

**Comment by svaarala** [comment]
I'd like to add a void pointer userdata argument to `duk_safe_call()` and deprecate the previous function. Quite often (more often than not I'd say) one needs to pass C values to a duk_safe_call() target, which is currently done either via the value stack (cumbersome) or globals (or similar).

**Comment by svaarala** [comment]
For buffer support it'd be nice to remove `Duktape.Buffer`, as it has no real reason to exist with `ArrayBuffer` supported. It could be removed entirely, and `ArrayBuffer` could take its place where it matters. For example, plain buffer values should object coerce to `ArrayBuffer` (instead of `Duktape.Buffer`).

Another possible change would be to deprecate plain buffer values entirely as they're custom types. Plain buffers do have the merit of being very memory conservative compared to `duk_hbufferobject` values, so they are useful at least in low memory environments.

**Comment by fatcerberus** [comment]
I never could figure out the difference between Duktape.Buffer and plain buffers, honestly.  What does the former do that the latter doesn't?

**Comment by svaarala** [comment]
The relationship is similar to how a plain string and a `String` object relate to each other:

- A plain string is a primitive value and has no property storage. Same for plain buffer.

- A `String` object wraps an underlying plain string, and provides property storage. You can get the underlying string using `.valueOf()`. Same for `Duktape.Buffer`.

**Comment by svaarala** [comment]
Somewhat related - I'm writing a Duktape 1.3 "buffers howto" right now: https://github.com/svaarala/duktape-wiki/pull/30

It's not finished yet, but feedback is appreciated, especially for making the intro part as easy to approach as possible. It perhaps needs some very basic examples to get started etc. (Discussion about that in the duktape-wiki repo :-)

**Comment by fatcerberus** [comment]
That's a good idea, the buffer support is one of those dark corners of Duktape that I always had a hard time wrapping my head around.  ArrayBuffers I seemed to have no problem with though, despite them being much more complex...

**Comment by fatcerberus** [comment]
Regarding refcount-only: Would it be possible to instead rework pause handling so that objects are still refzero queued, and then pump the whole queue on resume?  That should ensure only debugger-created objects get freed (unlike a forced mark and sweep)

**Comment by svaarala** [comment]
Yes, but that would require `duk_hstring` to have link pointers so that it could be queued to the refzero list. As things are now, they don't have link pointers because that's handled by the string table. This might change (for other reasons), though.

**Comment by fatcerberus** [comment]
Do `duk_pop_2()` and `duk_pop_3()` need to be part of the public API?  I understand that they're good to have internally for footprint (smaller call sites), but for outside callers `duk_pop_n` should be enough, no?

**Comment by svaarala** [comment]
The code emitted for popping N elements (with a variable count loop) vs. popping a fixed number of elements is much worse performance-wise. Having the most common cases (popping 1-3 elements) allows these API calls/macros to be performance optimized if necessary. But it's admittedly a bit of a grey area.

**Comment by fatcerberus** [comment]
Theoretically you could add special cases for 1-3 elements, however this would probably also be worse performance than the dedicated functions due to branching, and isn't really good for code clarity either.  So I see what you're saying here.

**Comment by fatcerberus** [comment]
While I'm thinking about it `print` and `alert` can be removed now since we can use AppNotify for tracing, and printing to stdout is easy enough for the user to just add a Duktape/C call to do it.

**Comment by svaarala** [comment]
Leftovers moved to #1217.
