### ISSUE TITLE
Fixes for 1.2.4 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#302]
- [x] Try-finally finalizer side effect issue, merge TRYCATCH clobbering fix #287
- [x] Missing 'act' relookup #305
- [x] Windows include guard #312
