### ISSUE TITLE
Fixes for 1.2.5 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#338]
- [x] duk_is_primitive() for invalid index (must provide as an API function to avoid changing function/macro status of duk_is_primitive()) #337
- [x] Assignment reg-bound RHS handling #381
- [x] parseInt() radix 16 handling #414
- [x] Numconv bool comparison #264
- [x] Segfault when compiling typescriptServices.js #449
- [x] Update releases in master
