### ISSUE TITLE
Fixes for 1.3.1 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#339]
- [x] Assignment reg-bound RHS handling #381
- [x] Nested property assignment #427, #428 (probably addressed already in #381)
- [x] Property assignment with inner expression mutating base value #429
- [x] parseInt radix 16 handling #414
- [x] Segfault when compiling typescriptServices.js #449
- [x] Update releases in master
