### ISSUE TITLE
Fixes for 1.4.1 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#533]
- [x] Refcount finalizer rescue: #531
- [x] Genconfig feature option defaulting: #550
- [x] Debugger Eval dbg_processing handling: #562
- [x] Debugger detach/reattach bug: #599
- [x] Debugger write_cb NULLing bug for single byte write: #599
- [x] External buffer alloc bug: #618
