### ISSUE TITLE
Fixes for 1.3.3 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#534]
- [x] Refcount finalizer rescue: #531
- [x] Debugger recursive re-entry after detach: #599 => not applicable, the bug was related to split detach handling required by detach notify which is not supported in 1.3.x
- [x] External buffer alloc bug: #618 

#599 fixes two other issues not directly relevant for 1.3.3:
- Detach/reattach state handling bug: there's no reattach-in-detached-callback support in 1.3.x and no split into detach1/detach2, so shouldn't need to be applied
- Debugger write_cb NULLing on a write error: there's no Detaching notify so this change should not be needed
