### ISSUE TITLE
Fixes for 1.5.1 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#722]
- [x] JSON encoding shadowed variable #794
- [x] Duktape.info() for `duk_hbufferobject` #804
- [x] Compile error with pointer compression and probe string table #850
- [x] JSON serialization of buffer objects #867 => Skipped because the diff seems too large compared to the potential benefit
- [x] String table side effect issue when string data pointer/length may be invalidated by a finalizer #884
- [x] Related: mark 1.3.x no longer maintained, 1.4.x could get #884 and then be last release?
- [x] Lightfunc constructor handling bug #895
- [x] `__FILE__` and `__LINE__` in public API header #897
- [x] AmigaOS3 math replacements #932
- [x] Gcc/clang "unused" attribute for internal functions #916 #942

**Comment by fatcerberus** [comment]
Seems you've amassed quite a list of fixes for 1.5.1.  Luckily none of these affect me and 1.5.0 has been rock solid in minisphere. :)

**Comment by svaarala** [comment]
These are quite hard to encounter in practice, which is also why I haven't released 1.5.1 yet (= it's not urgent).

**Comment by svaarala** [comment]
I'll do some merging to bring in the fixes to v1-maintenance and v1.5-maintenance. Maybe it'd be a good time to release 1.5.1.

**Comment by svaarala** [comment]
I'll skip backporting the fix to #867 for two reasons:
- The diff is relatively large.
- The fix causes ArrayBuffers to JSON serialize as objects - but because their index properties are enumerable in 1.x the result is probably not what one would expect. Indexes are non-enumerable in 2.x but including that fix in 1.5 would be too large a change in behavior w.r.t. semantic versioning guarantees.
