### ISSUE TITLE
Duktape 2.x buffer behavior changes

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#865]
This issue tracks the overall buffer behavior changes in Duktape 2.x:
- [x] Change plain buffers to behave like ArrayBuffers for Ecmascript code - #864
- [x] Remove Duktape.Buffer, use ArrayBuffer instead - #739
- [x] With Duktape.Buffer gone, how to get at plain buffer from Ecmascript (if at all; lightfuncs also can only be created from C code)? => ArrayBuffer.allocPlain()
- [x] `DUK_USE_BUFFEROBJECT_SUPPORT`; more ArrayBuffer functionality (like ArrayBuffer.slice?) when bufferobject support disabled? - #889 => For now all Ecmascript bindings are disabled when buffer object support is disabled
- [x] Should Duktape.dec() return a plain buffer or an ArrayBuffer object? Now returns a plain buffer.
- [x] Internal document or Wiki article detailing changes made (separate from buffer howto which should just describe current state) => Release notes

Minor issues / cleanups left over from main merges (to be fixed or promoted into issues):
- [x] Should `duk_buffer_to_string()` accept buffer objects too? => Yes, changed in #875
- [x] Idiom for creating a plain buffer from Ecmascript code; `Uint8Array.allocPlain(4)`
- [x] Idiom for creating a Node.js buffer sharing the same ArrayBuffer (now a copy is made); now follows Node.js Buffer behavior with ArrayBuffer having special (no copy) handling
- [x] Idiom for creating an ArrayBuffer from a Node.js buffer, sharing the same underlying buffer; now follows newer Node.js Buffer behavior so that you can just say `x.buffer`
- [x] Idiom for string-to-buffer in Ecmascript code => `ArrayBuffer.allocPlain('foo')` for plain buffers, no easy way for typed arrays, `new Buffer('foo')` for Node.js Buffers
- [x] Idiom for buffer-to-string in C code
- [x] Idiom for buffer-to-string in Ecmascript code => 1:1 coercion to be removed #1005, Node.js Buffer does an UTF-8 decoding step
- [x] Idiom for creating an internal key in Ecmascript code => not to be supported anymore #1005 by default
- [x] Should typed array (and DataView) constructors set `view.buffer` to the plain buffer (non-compliant result; but also input is non-compliant) or ToObject() coerced plain buffer (actual ArrayBuffer object backing to the same plain buffer)? => Now object coerced for typed arrays, DataView rejects plain buffers which mimic Uint8Array (also rejected by DataView)
- [x] ArrayBuffer and plain buffer non-standard properties #870

**Comment by fatcerberus** [comment]
With `Duktape.Buffer` gone and plain buffers acting like primitive ArrayBuffers, is there any real use case for accessing the plain buffer from Ecmascript code?  The only thing I can think of would be passing it back to a Duktape/C function, but in that case any buffer object is just as good as any other, since C code can always extract the underlying storage from any of them.

**Comment by svaarala** [comment]
It would be useful if you wanted to manipulate the plain buffers (in a Duktape specific way) in Ecmascript rather than in C code. It's not necessarily preferable to do things in C.

**Comment by svaarala** [comment]
Somewhat related - one option I've been looking into would be to remove the concept of an "underlying plain buffer" from `duk_hbufobj` (which represents ArrayBuffer, typed arrays, and Node.js buffer). Instead, both plain buffers and `duk_hbufobj` objects would directly reference/own their data storage.

This would remove one level of indirection from `duk_hbufobj` handling. One downside is that both plain buffers and buffer objects would need to support different buffer variants (fixed, dynamic, and external). However, maybe that support could be narrowed a little bit - for example, maybe external buffers could only be supported via a fully fledged ArrayBuffer.

Anyway, if this change is implemented then there's no need for a "get the underlying plain buffer" operation because there's no separate underlying plain buffer anymore. There's of course the underlying storage which can, at least in some cases, be shared.

**Comment by fatcerberus** [comment]
I guess what I was getting at above was, what could I do with the result of (hypothetical) `Duktape.plain(bufobj)` that I couldn't already do with `bufobj.buffer`?  In Duktape 2.x the two objects are indistinguishable to Ecmascript code because both will act like ArrayBuffers.

**Comment by svaarala** [comment]
The same thing you'd want do in C when dealing with plain buffers, e.g. save memory?

**Comment by fatcerberus** [comment]
I guess that's a good point.

Anyway, I wouldn't be against making ArrayBuffer and Node.js Buffer objects maintain their own allocations.  Honestly the extra level of indirection is sometimes confusing because I forget I have to push a fixed buffer _before_ calling `duk_push_buffer_object()`.

It might also be more in line with the Khronos/ES6 specs which assume ArrayBuffer is the basic primitive.

**Comment by svaarala** [comment]
Yeah, that indirection is indeed a bit confusing for ArrayBuffer at least. For typed arrays the indirection is more or less necessary - several typed arrays may back to the same ArrayBuffer with a slice offset etc. For Node.js buffers a backing ArrayBuffer would again be odd, which means there would be two different conceptual primitive buffer types.

For typed arrays it's not enough to copy the raw pointer/length over when creating the typed array if the backing ArrayBuffer is configurable (like a dynamic or external buffer). Khronos/ES6 doesn't support ArrayBuffer resizing but it'd be annoying if creating a typed array "froze" the ArrayBuffer. (By freezing the backing buffer and maintaining a reference to it it'd probably be safe to copy the pointer/length; for fixed buffers only the reference would be needed.)

If that indirection is present for typed arrays, they need to look up the backing ArrayBuffer which may either be plain (`duk_hbuffer_xxx`) or a full object (`duk_hbufobj`). This is a bit more involved than the current case where the backing buffer is always a plain buffer. But overall it'd probably be simpler.

**Comment by fatcerberus** [comment]
Potentially relevant: Node.js changed the semantics of the Buffer object in 6.x.  Notably you no longer use the Buffer constructor, and Buffer now seems to inherit from Uint8Array.

**Comment by svaarala** [comment]
Forgot about that - quite relevant, yes :) I'll have to digest that change separately I think, added to description.

**Comment by svaarala** [comment]
It might be possible to remove direct Node.js Buffer support and let the user implement that instead (and provide extras/nodejs-buffer for that). However, the C API supports Node.js Buffer directly too.

**Comment by fatcerberus** [comment]
A quick test confirms that inheritance relationship:
```
C:\Users\fatce>node --version
v6.3.0

C:\Users\fatce>node
> (Buffer.alloc(100) instanceof Uint8Array)
true
>
```

Also, the Node 6.3 REPL appears to be glitchy and doesn't always want to print the result of an expression, instead it prints useless blank lines. :-/

**Comment by fatcerberus** [comment]
I wouldn't be against moving Node.js Buffer support into an extra, however note that some features require engine support, like `Buffer.allocUnsafe()`.

**Comment by svaarala** [comment]
Hmm, what support is required? Buffer sharing is not required (just allowed, as far as I can tell) and not implemented by Duktape at present. Zeroing memory that's not guaranteed to be initialized is also not a compatibility issue, although that zeroing is unnecessary.

**Comment by fatcerberus** [comment]
True that zeroing an "uninitialized" buffer doesn't hurt anything, although it's worth noting that code explicitly calling `.allocUnsafe()` usually does so for performance reasons (because the buffer is going to be filled immediately afterward, e.g.).  That said, Node.js itself provides a command-line option to zero all buffers anyway, so as you said, not a compatibility issue.

The other feature I thought might be an issue to make external was `buffer.toString()` but thinking about it now, if the extra is written in C that's not actually a problem since the function can just call `duk_push_lstring()` passing the buffer's memory location to get a UTF-8 representation.

**Comment by fatcerberus** [comment]
Just putting this here as a reminder re: virtual index compliance: #257 :)

**Comment by svaarala** [comment]
Makes sense to fix that also, thanks.

**Comment by fatcerberus** [comment]
Do plain buffers act like ArrayBuffers even if buffer object support is disabled, or do they work like before in that case?

**Comment by svaarala** [comment]
At the moment they work mostly like before: you can create plain buffers from both C and Ecmascript code, and they will have virtual properties as normal. They'll also inherit from ArrayBuffer.prototype (which now must exist even when buffer object support is disabled) but the inherited methods are stubs that will throw. So, for example, `plain.slice(3, 7)` will throw.

**Comment by svaarala** [comment]
Right now with bufferobject support disabled you can still push an ArrayBuffer from C code (the Ecmascript constructor won't work though). I'm planning to remove that: the main goal of disabling bufferobject support is to save footprint, and support for the full ArrayBuffer object pulls in a lot of stuff that wouldn't otherwise be needed. I'll do that in a separate pull.

**Comment by fatcerberus** [comment]
Yeah, that's why I asked.  I would expect plain buffers to work as before with bufferobjects disabled and not inherit from ArrayBuffer.  In fact I would expect the ArrayBuffer and typed array constructors to not exist at all in that case.

**Comment by svaarala** [comment]
Hmm, that alternative would be roughly:

- Plain buffers would have virtual own properties to allow content to be manipulated.
- Plain buffers would inherit from Object.prototype (not ArrayBuffer.prototype). One wouldn't normally access any inherited properties when buffer objects are disabled, so maybe this is OK.
- `Object.prototype.toString()` would still print `[object ArrayBuffer]` because that's based on the internal class which is virtual for a plain buffer.
