### ISSUE TITLE
Fixes for 1.5.2 release

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#945]
- [x] Genconfig boolean comparison #954
- [x] duk_put_prop_xxx() shared value stack slot for target object and property value #959
- [x] RegExp executor zero buffer data assumption #978
- [x] `<op>` eval order #992
- [x] String.fromCharCode non-BMP behavior when compliant behavior (not the default) enabled #1046
- [x] Refcount broken asserts #1090 => nothing to fix in 1.x
- [x] Delprop e_idx stability issue #1096; needs an adapted fix because no NORZ macros
- [x] Use bare object for `Duktape.modLoaded[]` to avoid module names matching `Object.prototype` properties from being ignored #1127
- [x] duk_hcompfunc data != NULL assumptions #1144
- [x] JX/JC fastpath handling of array gaps #1149
- [x] Object.isPrototypeOf() memory safety fix #1163

**Comment by svaarala** [comment]
Well, isn't *any* bug fix a semantic versioning violation if someone is relying on the buggy behavior?

**Comment by svaarala** [comment]
... that is, unless bug fixes are considered exempt from versioning guarantees.

**Comment by svaarala** [comment]
We've actually discussed this at length earlier - but here's what semver says about PATCH releases:

> PATCH version when you make backwards-compatible bug fixes.

and:

> A bug fix is defined as an internal change that fixes incorrect behavior.

These may seem clear but are actually very vague if you look at them more closely.

One problem is that *by definition* any bug fix will be backwards incompatible at least with respect to how the release behaves when the bug is present or absent. If it wasn't possible to write a program that behaved one way with the bug present, and a different way when it is absent, there would literally be no need to fix the bug. (There are some security bugs like side channels which may not be directly apparent from an API, and they're arguably a different case.)

That may seem like splitting hairs but it's actually not: sometimes a user encounters a bug without realizing it, and writes a workaround which actually relies on the bug being present. A patch level fix to such a bug will break the workaround and thus be backwards incompatible.

**Comment by svaarala** [comment]
So coming back to this specific case: (This is pretty much academic and not necessarily a very good use of development time, but let's indulge ;)

- Is the change a bug fix? Most certainly, it fixes the case when you `require('toString')`.

- Is the change backwards compatible? "No" in the strictest sense (I don't think there has been a single fix that would fit that requirement) that no outward behavior changes. "Yes" in the sense that `Duktape.modLoaded[]` is described as a "Internal tracking table for loaded modules, maps resolved identifier to module metadata object", and there are no explicit guarantees as to what its prototype is.

- Is the fix an "internal change"? In the strictest sense "no" because it has externally visible impact. "Yes" in the sense that Duktape.modLoaded[] has very few public guarantees other than tracking loaded (cached) modules.

More practical concerns:

- Is it likely that some code is relying on the buggy behavior? In other words, some code would rely on `requre('toString')` returning undefined without doing anything. I would expect "no" to be the answer.

- On the other hand maybe some code might have done `String(Duktape.modLoaded)` for e.g. printing its type. That code would break because a bare object cannot be string coerced. Then again, there have never been any guarantees that `String(Duktape.modLoaded)` would work either. So as it often happens, there may be application dependencies on behavior that hasn't been guaranteed in the API contract.

**Comment by fatcerberus** [comment]
You understand I was just ribbing you, right?  I would have fixed the bug too :) (there are some quite militant semver proponents I'm sure would disagree with us though)

**Comment by svaarala** [comment]
I actually didn't - the question is valid and I find semver sometimes awkward to work with because there's a lot of grey area. In the end one needs to make many judgement calls as to what is "backwards compatible" for example.

But if you really didn't want an answer, you shouldn't ask the question ... :)
