### ISSUE TITLE
Add ES6 Symbol support for Duktape 2.x

### ISSUE THREAD

**Issue by svaarala** [svaarala/duktape#981]
- [x] Document and prototype implementation approach #980
- [x] Basic testcase exercising the most important semantic behavior for symbols
- [x] Add new internal class and Symbol constructor
- [x] Add basic ES6 semantics like string coercion, `typeof`, and property key lookup handling
- [x] Add support for "hidden Symbols" similar to #979 semantics, to be decided if 0xFF prefixed internal keys are automatically "hidden" or not
- [x] Code comment changes for terminology
- [x] Internal documentation changes
- [x] Website and API document changes
- [x] Wiki changes
- [x] Related buffer issue: remove 1:1 buffer-to-string binding (more relevant with #979 and symbols maybe)?
- [x] 2.x migration notes
- [x] Releases entry

**Comment by fatcerberus** [comment]
I don't see this in the checklist: Will the initial implementation include any default built-in symbols like @@toStringTag?

**Comment by svaarala** [comment]
I added a few such symbols for testing the built-in format - but they're not functional. For example, `Object.prototype.toString()` won't look up @@toStringTag now.

**Comment by svaarala** [comment]
So what I'd like to figure out first is how to represent symbols internally. Once that's solid, symbol-related APIs and internal behaviors like coercion handling, @@toStringTag etc can follow.

Because there's quite a lot of stuff I'm kind of on the fence how to handle it so that they can be disabled for low memory ES5 targets. Maybe there needs to be a catch-all define for DUK_USE_ES6 which is used to guard any semantics which don't deserve a specific define... Not sure.
